### ISSUE TITLE
How to use the log snippet?

### ISSUE THREAD

**Issue by d0t15t** [ecosse3/nvim#105]
In a previous version of ecovim, it was possible to add a `console.log(...)` with a snippet by typing `log`. 
Now it seems to have changed, and we can use a variable? How does this work?
Many thanks!

**Comment by Akiletour** [comment]
![CleanShot 2022-10-18 at 12 24 43](https://user-images.githubusercontent.com/1524422/196405130-6c4d24f7-0af5-46a9-9fec-2b46d4baaa1e.jpg)

In my project, it's now the last autocompletion entry.

1 month ago, @ecosse3 applied a fix in order to deprioritize snippets https://github.com/ecosse3/nvim/commit/9dccb4b48a8789a6019f6c0533542b61bdfa77b7

You can remove the `deprioritize_snippet` in the comparators object (line 168) to rollback

**Comment by ecosse3** [comment]
@d0t15t Does previous comment solve your issue? I can confirm that order of snippets has been deprioritized.
