### ISSUE TITLE
No Lsp for Javascript and Typescript

### ISSUE THREAD

**Issue by scypurple** [ecosse3/nvim#109]
I don't know if it's a bug or if I missed something
**Environment**
+ mac iterm2 Build 3.4.16
+ neovim 0.8.0
+ ecovim 2.4.2 
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/14716045/197755854-26de8b8c-8809-4b1a-8b22-837261332be2.png">
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/14716045/197756014-ece40953-c6d6-4365-a5c8-ff2579454682.png">
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/14716045/197756271-3d091a28-c6a7-4fe7-9d4c-cfca154efbfb.png">
I don't know how to solve the problem `root directory: Not found`
everytime I use Mason update all files, it's succussful but useless.

**Comment by ecosse3** [comment]
Hi. I checked in official LSP config documentation for neovim and this behaviour is expected because `tsserver` requires a root directory to match specific patterns `'tailwind.config.js', 'tailwind.config.ts', 'postcss.config.js', 'postcss.config.ts', 'package.json', 'node_modules', '.git'` to start the server as default option described [here](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#tsserver).

**Comment by scypurple** [comment]
I add the root_dir into `setup.lua` , it worked, thank you.
