### ISSUE TITLE
Need support for few more LSP

### ISSUE THREAD

**Issue by rajcspsg** [ecosse3/nvim#19]
Hi,

Thanks for the amazing neovim config. Could you please add support for below languages - 

1. java - [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls)
2. scala - [nvim-scala](https://github.com/scalameta/nvim-metals)
3. clojure - there is a sample config available in this [repo](https://github.com/rafaeldelboni/nvim-fennel-lsp-conjure-as-clojure-ide) 

I don't know lua very much if you could add these 3 languages support it would be great

**Comment by ecosse3** [comment]
Hi.

I will not add additional LSPs to my config by default because it's meant to be a Frontend Development Neovim config. You can easily add another LSP server by `:LspInstall` command.

Just type `:LspInstall jdtls` and `:LspInstall clojure_lsp` and it will work. You can add nvim-scala on your own too.
