### ISSUE TITLE
typescript (tsx) format indentation not working

### ISSUE THREAD

**Issue by marcelothomaz** [ecosse3/nvim#62]
Hi,

Not sure this is related to nvim builds:
NVIM v0.8.0-dev+452-gb2ed439bd
Build type: Release
LuaJIT 2.1.0-beta3

<Leader>cf nor vim.lsp.buf.format* works. 
Only `ggVG` then `=` indents the file.

I have done nothing different or any customization

**Comment by ecosse3** [comment]
Should be fixed on `dev` branch for now. In neovim 0.8 recently API has changed and modifying a server's capabilities is not necessary thanks to the `vim.lsp.buf.format` API. By that I have enabled both eslint & tsserver formatting and they shouldn't not conflict with each other.

I didn't notice that doesn't work because I mostly use eslint for formatting which didn't break 😊 Thanks for the issue!

**Comment by ecosse3** [comment]
Thanks, fix is not available in the master branch. Closing issue.
