### ISSUE TITLE
Telescope hanging on grep

### ISSUE THREAD

**Issue by matthewcm** [ecosse3/nvim#64]
Hey.

I am getting huge memory spikes after running `builtin.grep_string()` or the picker rg.

- Results in nvim completely hanging for about 2 minutes or so, before exiting telescope with error message:
- error executing vim.schedule lua callback
- buffer previewer expected lua number

- Git files does not hang, or the other finders. I have tried the fzf-native plugin and the fzy-native plugin with no luck.
- The grep string seems to only cause issues on particular searches.
- if I grep 'hi' in my project, I get over 1000 matches, and I am able to navigate between the matches fine.
- However if I search 'player' in my project, I get 500 matches, and telescope completely hangs the nvim client. 

![image](https://user-images.githubusercontent.com/13544609/174782040-224d2755-d55b-4266-934d-e64f66634779.png)
Seeing this odd memory spike behaviour after running grep.

Tried to replicate this on a minimal nvim init.lua with only Telescope installed, and saw that Telescope runs fine, so this is a matter of plugin conflict, or some other performance issue. I am running this on a pretty powerful 16Gb laptop.

**Comment by ecosse3** [comment]
I guess it can be some problem with your personal PC somehow because for me it works great after `fzf-native` was made for Telescope. You could try to open an issue directly in telescope repo to figure it out.

Did you run `:checkhealth` for looking for any possible problems?

Could you check if you are in your working directory via `:pwd`? I tried to grep `import` word with over 15000 matches and it works so quickly. If I `:cd ~` to my home directory my neovim crashed after 800,000 found results which is huge.

I guess it can be just hardware/telescope issue. Probably it's not much matter of my config.

**Comment by matthewcm** [comment]
Thanks, i'll try some things out. I've tried on another PC, with 64GB ram, and a very fast CPU and still seeing this issue.

My own NVIM setup of telescope did not have any problem. I've also tried to use fzy-native with the ecovim setup, and still seeing the issue. So I am not too sure, what is really conflicting here.

Maybe i'll start from a simple setup and keep adding things in until i notice the issue. HealthCheck does not seem to provide anything too useful.

**Comment by matthewcm** [comment]
I found it. Seems to be https://github.com/NvChad/nvim-colorizer.lua 
The autocommand is attaching to the telescope buffers.

**Comment by ecosse3** [comment]
@matthewcm Thanks for looking for that. I'll disable this extensions for telescope buffers and see the results. Will let you know.

**Comment by ecosse3** [comment]
@matthewcm Fixed on `dev` branch. I'll do a release soon so it will be available on master.
