### ISSUE TITLE
Some Plugins Can't Install

### ISSUE THREAD

**Issue by umtdemr** [ecosse3/nvim#7]
Hi, 
i want to try out your nvim configuration. But i got some errors. First error caused by "impatient" and i solved it by commenting first line in init.vim `lua require('impatient')`. (After the :`PackerInstall` command finished i added that line again)

The error that i couldn't solve is caused by plugins. Some plugin's couldn't install. I tried install them via :PackerInstall but that did not work. 

![2021-10-18_12-28_1](https://user-images.githubusercontent.com/61540809/137705401-17628505-3c1d-478c-8736-2ff38a8d8683.png)
![2021-10-18_12-28_2](https://user-images.githubusercontent.com/61540809/137705405-f4d2028f-417a-4d15-ab05-592335f9a190.png)
![2021-10-18_12-28](https://user-images.githubusercontent.com/61540809/137705408-9e03ad68-0963-44e0-95ad-353b8577591a.png)

When i try to open neo vim after those errors:

![2021-10-18_12-17](https://user-images.githubusercontent.com/61540809/137703676-3e5b96d1-d540-4626-9891-05d9c4a49ce4.png)

**Comment by ecosse3** [comment]
Yes, currently there is problem with impatient because it needs to be always run before all another imports but it's only during before first installation. It will be fixed when I provide a shell script to install my neovim instance.

About tsutils, could you check if removing "after" from https://github.com/ecosse3/nvim/blob/master/lua/plugins.lua#L146 can help with that? You need to run :PackerSync.

I'll remove `fzy-native` package from plugins because it's not used anymore by my neovim (I use fzf-native which is much faster).

Another issues can be related to plugins itself. You can open an issue in their repo but actually they works for me now. You can check in `~/.local/share/nvim/site/pack/packer/start/{plugin_name}` if they have some git changes. If yes, you need to revert them and probably they will install correctly. That's some issue related to Git itself. Let me know if that works.

**Comment by umtdemr** [comment]
I tried again after your last commit and your reply but i got errors back.  It might be because of packer or my system. I got warning when i try to `:PackerInstall` like this:

![new_err](https://user-images.githubusercontent.com/61540809/137796319-2f72466c-44f7-41b2-8425-73b626096df9.png)


The rest is already as I mentioned before.

**Comment by umtdemr** [comment]
I can't believe but it works now. Literally I only just ignored  errors.

Thank you for sharing your amazing configuration it works so well. :+1:
