### ISSUE TITLE
Support For ReactJS - Auto Close Tag

### ISSUE THREAD

**Issue by FoxNQ99** [ecosse3/nvim#83]
hello, thank you for this project, this project helped me a lot .
 i want to add plugin https://github.com/alvan/vim-closetag but i dont know how to add a plug, can you help me?, 
i use JS and TypeScript , thank you very much

**Comment by alfredosdpiii** [comment]
Go to the lua folder and edit plugins.lua file and instead of Plugin 'alvan/vim-closetag' use use 'alvan/vim-closetag'

**Comment by ecosse3** [comment]
I'll consider adding a similar plugin but for now, CMP suggestion for a closing tag with LSP is enough for me when working daily. Auto closing tags sometimes can be annoying when you don't want to close them immediately.

You should check [nvim-ts-autotag](https://github.com/windwp/nvim-ts-autotag) instead of vim-closetag.

**Comment by d0t15t** [comment]
> CMP suggestion for a closing tag with LSP is enough for me when working daily.

Could you please elaborate on this? The only suggestions I'm getting are seen below, but probably I'm not understanding something.

![image](https://user-images.githubusercontent.com/3645818/184806577-9fa5faf7-3f97-459f-952e-888591362ab1.png)

**Comment by ecosse3** [comment]
@d0t15t That's correct. You can enable in `config.lua`:

```lua
completion = {
  select_first_on_enter = true
},
```

so in that case closing tag will be automatically selected. Then you just press enter to close it. I consider using auto closing tag more annoying than useful in most cases so that's why I don't use them. Fell free to add it to your plugins in Ecovim setup.
