### ISSUE TITLE
Emmet

### ISSUE THREAD

**Issue by hitfm00** [ecosse3/nvim#96]
I think will be cool if you will add `Emmet`, because it's hard to write tags for example `<div></div>`
I just want to write `div` and use `tab` and it will be convert to `<div></div>` :)
It's just proposition

**Comment by ecosse3** [comment]
Hi. Feel free to add it to the config for yourself, it's just one line in `setup.lua`.

I am using it for couple of weeks now but one thing which is very annoying to me is that I cannot sort Emmet Snippets based on priority, because LSP priority in Ecovim config is on the top and Emmet Snippets counts as LSP...

Because of that behavior Emmet Snippets are always on the top which is something I really don't like:
 
![image](https://user-images.githubusercontent.com/17691791/191273897-e19a448b-0173-47bf-93bd-2e8f232da570.png)

If I will figure out or someone can help me how to change this behavior and make Emmet LS less important than other LSPs I will add it to the config as default.

**Comment by Akiletour** [comment]
Hi @ecosse3 ,

I found something on Reddit : 
https://www.reddit.com/r/neovim/comments/woih9n/comment/ikbd6iy/?utm_source=share&utm_medium=web2x&context=3

What did you think about his solution ?

**Comment by ecosse3** [comment]
Thank you @Akiletour. That works great, it's always on the bottom so it's easy to reach it with <Ctrl-K> or Up Arrow. Merged to dev and it will be merged to master within the next release (a week probably).
